/*****************************************************************************************/
/************ STM32f103xx PortConfiguration                *******************************/ 
/************ File Name  : Port_Cfg.c                       *******************************/ 
/************ Author     : Yasmeen Ibrahim                 *******************************/           
/************ Description:                                 *******************************/
/*****************************************************************************************/

#include "Port_Cfg.h"

extern Port_ConfigType Port_Config_Global; 
Port_Config_Global.arrPort_PinConfig[PortNumberOfPortPins] = 
{
  /* PortPinId  , PortPinMode      , PortPinDirection, PortPinDirectionChangeable, PortPinInitialMode, PortPinLevelValue , PortPinModeChangeable */
    {PORTA_PIN0 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTA_PIN1 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
	{PORTA_PIN2 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTA_PIN3 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTA_PIN4 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTA_PIN5 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTA_PIN6 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTA_PIN7 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTA_PIN8 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTA_PIN9 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTA_PIN10, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTA_PIN11, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTA_PIN12, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTA_PIN13, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTA_PIN14, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTA_PIN15, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTA_PIN16, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTA_PIN17, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTA_PIN18, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTA_PIN19, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTA_PIN20, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTA_PIN21, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTA_PIN22, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTA_PIN23, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTA_PIN24, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTA_PIN25, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTA_PIN26, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTA_PIN27, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTA_PIN28, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTA_PIN29, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTA_PIN30, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTA_PIN31, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
	
	{PORTB_PIN0 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTB_PIN1 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTB_PIN2 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTB_PIN3 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTB_PIN4 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTB_PIN5 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTB_PIN6 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTB_PIN7 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTB_PIN8 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTB_PIN9 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTB_PIN10, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTB_PIN11, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTB_PIN12, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTB_PIN13, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTB_PIN14, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTB_PIN15, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTB_PIN16, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTB_PIN17, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTB_PIN18, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTB_PIN19, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTB_PIN20, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTB_PIN21, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTB_PIN22, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTB_PIN23, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTB_PIN24, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTB_PIN25, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTB_PIN26, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTB_PIN27, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTB_PIN28, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTB_PIN29, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTB_PIN30, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTB_PIN31, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
	
    {PORTC_PIN0 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTC_PIN1 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTC_PIN2 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTC_PIN3 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTC_PIN4 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTC_PIN5 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTC_PIN6 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTC_PIN7 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTC_PIN8 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTC_PIN9 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTC_PIN10, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTC_PIN11, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTC_PIN12, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTC_PIN13, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTC_PIN14, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTC_PIN15, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTC_PIN16, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTC_PIN17, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTC_PIN18, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTC_PIN19, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTC_PIN20, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTC_PIN21, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTC_PIN22, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTC_PIN23, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTC_PIN24, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTC_PIN25, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTC_PIN26, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTC_PIN27, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTC_PIN28, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTC_PIN29, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTC_PIN30, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTC_PIN31, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
	
    {PORTD_PIN0 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTD_PIN1 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTD_PIN2 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTD_PIN3 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTD_PIN4 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTD_PIN5 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTD_PIN6 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTD_PIN7 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTD_PIN8 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTD_PIN9 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTD_PIN10, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTD_PIN11, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTD_PIN12, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTD_PIN13, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTD_PIN14, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTD_PIN15, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTD_PIN16, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTD_PIN17, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTD_PIN18, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTD_PIN19, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTD_PIN20, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTD_PIN21, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTD_PIN22, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTD_PIN23, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTD_PIN24, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTD_PIN25, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTD_PIN26, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTD_PIN27, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTD_PIN28, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTD_PIN29, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTD_PIN30, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTD_PIN31, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
   
    {PORTE_PIN0 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTE_PIN1 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTE_PIN2 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTE_PIN3 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTE_PIN4 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTE_PIN5 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTE_PIN6 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTE_PIN7 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTE_PIN8 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTE_PIN9 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTE_PIN10, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTE_PIN11, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTE_PIN12, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTE_PIN13, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTE_PIN14, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTE_PIN15, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTE_PIN16, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTE_PIN17, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTE_PIN18, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTE_PIN19, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTE_PIN20, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTE_PIN21, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTE_PIN22, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTE_PIN23, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTE_PIN24, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTE_PIN25, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTE_PIN26, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTE_PIN27, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTE_PIN28, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTE_PIN29, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTE_PIN30, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTE_PIN31, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
   
    {PORTF_PIN0 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTF_PIN1 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTF_PIN2 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTF_PIN3 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTF_PIN4 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTF_PIN5 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTF_PIN6 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTF_PIN7 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTF_PIN8 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTF_PIN9 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTF_PIN10, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTF_PIN11, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTF_PIN12, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTF_PIN13, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTF_PIN14, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTF_PIN15, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTF_PIN16, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTF_PIN17, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTF_PIN18, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTF_PIN19, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTF_PIN20, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTF_PIN21, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTF_PIN22, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTF_PIN23, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTF_PIN24, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTF_PIN25, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTF_PIN26, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTF_PIN27, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTF_PIN28, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTF_PIN29, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTF_PIN30, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTF_PIN31, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
   
    {PORTG_PIN0 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTG_PIN1 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTG_PIN2 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTG_PIN3 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTG_PIN4 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTG_PIN5 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTG_PIN6 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTG_PIN7 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTG_PIN8 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTG_PIN9 , PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTG_PIN10, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTG_PIN11, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTG_PIN12, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTG_PIN13, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTG_PIN14, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTG_PIN15, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTG_PIN16, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTG_PIN17, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTG_PIN18, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTG_PIN19, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTG_PIN20, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTG_PIN21, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTG_PIN22, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTG_PIN23, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTG_PIN24, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTG_PIN25, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTG_PIN26, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTG_PIN27, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTG_PIN28, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTG_PIN29, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTG_PIN30, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 },
    {PORTG_PIN31, PORT_PIN_MODE_DIO, PORT_PIN_OUT    , True                      , PORT_PIN_MODE_DIO , PORT_PIN_LEVEL_LOW, True                 }
}                                                                                                                                               